### ISSUE TITLE
`find_in_batches` generates broken ElasticSeach query

### ISSUE THREAD

**Issue by bklang** [elastic/elasticsearch-rails#229]
The default call for `find_in_batches` on a model results in a broken ES query:

```
2.1.2 :013 > ChatterMessage.find_in_batches { |batch| p batch.count }
2014-09-04 16:25:00 -0400: GET http://10.203.175.32:9200/_search?_source=&_source_exclude=&_source_include=&allow_no_indices=&expand_wildcards=&explain=&ignore_indices=&ignore_unavailable=&preference=&q=&routing=&scroll=5m&search_type=scan&size=&source=&stats=&timeout= [status:400, request:0.003s, query:N/A]
2014-09-04 16:25:00 -0400: > {}
2014-09-04 16:25:00 -0400: < {"error":"ElasticsearchIllegalArgumentException[Failed to parse int parameter [size] with value []]; nested: NumberFormatException[For input string: \"\"]; ","status":400}
2014-09-04 16:25:00 -0400: [400] {"error":"ElasticsearchIllegalArgumentException[Failed to parse int parameter [size] with value []]; nested: NumberFormatException[For input string: \"\"]; ","status":400}
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":"ElasticsearchIllegalArgumentException[Failed to parse int parameter [size] with value []]; nested: NumberFormatException[For input string: \"\"]; ","status":400}
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/client.rb:102:in `perform_request'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-api-1.0.4/lib/elasticsearch/api/actions/search.rb:149:in `search'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-persistence-0.1.4/lib/elasticsearch/persistence/model/find.rb:111:in `find_in_batches'
    from (irb):13
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/railties-3.2.18/lib/rails/commands/console.rb:47:in `start'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/railties-3.2.18/lib/rails/commands/console.rb:8:in `start'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/railties-3.2.18/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

I can get close by specifying most of the missing options, but I still get an error about a missing scroll ID:

```
2.1.2 :012 > ChatterMessage.find_in_batches(size: 2, timeout: 5, source: '*', scroll: 5) { |batch| p batch.count }
2014-09-04 16:23:33 -0400: GET http://10.203.175.32:9200/_search?_source=&_source_exclude=&_source_include=&allow_no_indices=&expand_wildcards=&explain=&ignore_indices=&ignore_unavailable=&preference=&q=&routing=&scroll=5&search_type=scan&size=2&source=%2A&stats=&timeout=5 [status:200, request:0.004s, query:0.000s]
2014-09-04 16:23:33 -0400: > {}
2014-09-04 16:23:33 -0400: < {"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}
2014-09-04 16:23:33 -0400: GET http://10.203.175.32:9200/_search/scroll?scroll=5&scroll_id= [status:400, request:0.003s, query:N/A]
2014-09-04 16:23:33 -0400: < {"error":"ElasticsearchIllegalArgumentException[Malformed scrollId []]","status":400}
2014-09-04 16:23:33 -0400: [400] {"error":"ElasticsearchIllegalArgumentException[Malformed scrollId []]","status":400}
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":"ElasticsearchIllegalArgumentException[Malformed scrollId []]","status":400}
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.4/lib/elasticsearch/transport/client.rb:102:in `perform_request'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-api-1.0.4/lib/elasticsearch/api/actions/scroll.rb:57:in `scroll'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/elasticsearch-persistence-0.1.4/lib/elasticsearch/persistence/model/find.rb:120:in `find_in_batches'
    from (irb):12
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/railties-3.2.18/lib/rails/commands/console.rb:47:in `start'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/railties-3.2.18/lib/rails/commands/console.rb:8:in `start'
    from /Users/bklang/.rvm/gems/ruby-2.1.2/gems/railties-3.2.18/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by estolfo** [comment]
Closing as this is out of date.
