### ISSUE TITLE
Importing data of model from SQL View

### ISSUE THREAD

**Issue by lucasmedeirosleite** [elastic/elasticsearch-rails#299]
Hi! I have a model like this:

```ruby

class Artist < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  self.table_name = 'artist'

	mapping :dynamic => false  do
    indexes :name
  end

end

```
This model comes from a legacy database, and in fact it does not come from a table, it comes from a sql view.

The problem is when I run:

  ```
   rake environment elasticsearch:import:model CLASS='Artist' FORCE=y
  ```
I receive this error

```
   ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'artist.' in 'order clause': SELECT  `artist`.* FROM `artist`   ORDER BY `artist`.`` ASC LIMIT 1000
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:232:in `exec_query'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:240:in `select'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/relation.rb:611:in `exec_queries'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/relation.rb:493:in `load'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/relation.rb:238:in `to_a'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/relation/batches.rb:118:in `find_in_batches'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.8/lib/active_record/querying.rb:9:in `find_in_batches'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/elasticsearch-model-0.1.6/lib/elasticsearch/model/proxy.rb:80:in `method_missing'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/elasticsearch-model-0.1.6/lib/elasticsearch/model/adapters/active_record.rb:95:in `__find_in_batches'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/elasticsearch-model-0.1.6/lib/elasticsearch/model/importing.rb:119:in `import'
/Users/lucasmedeirosleite/.rvm/gems/ruby-2.1.3/gems/elasticsearch-rails-0.1.6/lib/elasticsearch/rails/tasks/import.rb:63:in `block (3 levels) in <top (required)>'
Mysql2::Error: Unknown column 'artist.' in 'order clause'

```

**Comment by karmi** [comment]
@lucasmedeirosleite Any news here?

**Comment by RKushnir** [comment]
The `find_in_batches` is the culprit, it adds the ordering. So it looks more like a Rails issue, not ES
