### ISSUE TITLE
Error when using basic template

### ISSUE THREAD

**Issue by bgrayburn** [elastic/elasticsearch-rails#313]
Running:
```
rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
```
Returning:
```       
apply  https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
/Users/bgrayburn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server key exchange B: bad ecpoint (OpenSSL::SSL::SSLError)
```

**Comment by karmi** [comment]
This runs fine for me -- it might have been a problem on the Github side. Please try it again and post an update!

**Comment by bgrayburn** [comment]
Thanks karmi, tried it again and it worked up until I got this:
```
     gemfile    mocha
/media/Storage/firstmilegeo/elasticSearchTest/01-basic.rb:123:in `apply': undefined method `comment_lines' for #<Rails::Generators::AppGenerator:0x007fa93982ca78> (NoMethodError)
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/actions.rb:217:in `instance_eval'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/actions.rb:217:in `apply'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.0/lib/rails/generators/app_base.rb:109:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `block in invoke_all'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `each'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `invoke_all'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.0/lib/rails/commands/application.rb:38:in `<top (required)>'
	from /Users/bgrayburn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require'
	from /Users/bgrayburn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.0/lib/rails/cli.rb:15:in `<top (required)>'
	from /Users/bgrayburn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require'
	from /Users/bgrayburn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.0/bin/rails:7:in `<top (required)>'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/bin/rails:23:in `load'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/bin/rails:23:in `<main>'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
	from /Users/bgrayburn/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```
Hope I'm not missing something obvious, thanks again for the help.

**Comment by karmi** [comment]
Hey, I've tried this with Ruby 2.0.0, and got the same SSL error you've mentioned. I think that's something related to that particular version.

I've tried to run it with Rails 3.2 (since that's what you use) and Ruby 2.1.5:

```
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]

$ /Users/karmi/.rbenv/versions/2.0.0-p0/bin/rails -v
Rails 3.2.21

$ ~/.rbenv/versions/2.1.5/bin/rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
```

And the application is generated successfully and runs. I suggest you run this with either Ruby 2.1.5 or 2.2.0 and Rails 3.2.21 or latest 4.x, and report back.

**Comment by karmi** [comment]
@bgrayburn Closing this issue, please reopen if the problem persists.

**Comment by frankolson** [comment]
I am getting a similar error when trying to generate the basic template:

```shell
apply  https://raw.github.com/elastic/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
https://raw.github.com/elastic/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb:39:in `apply': uninitialized constant #<Class:#<Rails::Generators::AppGenerator:0x00555fe6349c70>>::JSON (NameError)
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/actions.rb:224:in `instance_eval'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/actions.rb:224:in `apply'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/generators/app_base.rb:158:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/will/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/exe/rails:9:in `<top (required)>'
	from /home/will/.rbenv/versions/2.4.0/bin/rails:22:in `load'
	from /home/will/.rbenv/versions/2.4.0/bin/rails:22:in `<main>'
```

Ruby version: `2.4.0`
Rails version: `5.0.2`

Is this generator able to work with Rails 5?

**Comment by eggie5** [comment]
same issue on rails 5 ruby 2.2.5

**Comment by tostasqb** [comment]
Same here
```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]

$ rails -v
Rails 5.1.2
```
Open a different issue?
