### ISSUE TITLE
"Net::HTTP::Persistent::Error: too many connection resets" while updating

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch-rails#416]
Using Elasticsearch::Persistence::Model, I’m indexing hundreds of thousands of books, each with several chapters.  The chapters contain an attachment with the full text (using the attachment plugin). 

I’ve already created the index and imported the meta data.  Now, I’m trying to update the chapters with the attachments.

After successfully updating several thousand chapters, I got an error (“Net::HTTP::Persistent::Error: too many connection resets…”).

Any ideas how to correct this?  See below for models, execution code, and the error stack trace.

Models:
```
class Book
  include Elasticsearch::Persistence::Model

  index_name [Rails.application.engine_name, Rails.env].join('-')

  mapping do
    indexes :identifier, type: ‘string’
    indexes :title, type: ‘string’
    indexes :editor, type: ‘string’
    indexes :publication_date, type: ‘date’    
  end

  attribute :identifier, String
  attribute :title, String
  attribute :editor, String
  attribute :publication_date, Date
  …

  def chapters
    Chapter.search({
      query: {
        has_parent: {
          type: 'book',
        ...
    })
  end

  def index_attachments
    chapters.each do |chapter|          #line 55
      chapter.index_attachment(identifier)
    end
  end
  ...
end

class Chapter
  include Elasticsearch::Persistence::Model

  index_name [Rails.application.engine_name, Rails.env].join('-')

  mapping  _parent: { type: ‘book’ } do
    indexes :identifier, type: ‘string’
    indexes :author, type: ‘string’
    indexes :attachment, type: 'attachment', path: 'full', fields: {
      attachment: {
        type: 'string',
        term_vector: 'with_positions_offsets',
        store: true
      } }
  end

  attribute :identifier, String
  attribute :author, String
  attribute :attachment

  …

  def index_attachment(book_identifier)
    filename = “#{book_identifier}_#{identifier}.pdf"
    path = path_for_book_and_chapter_identifiers(book_identifier,  identifier)
    
    if !File.exist?(path + filename)
      return false
    end
   
    encoded_attachment = Base64.encode64(open(path + filename) { |file| file.read })
    self.update({attachment: encoded_attachment}, {parent: book_identifier})          #line 40
  end
  …
end
```

Executed code:
```
Book.all.each do |book|
  book.index_attachments
end
```

Error:
```
Net::HTTP::Persistent::Error: too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 0 requests on 41759660, last used 1433038623.4439945 seconds ago
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:211:in `write'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:185:in `block in write'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:202:in `writing'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:184:in `write'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http/generic_request.rb:184:in `send_request_with_body'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http/generic_request.rb:130:in `exec'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1412:in `block in transport_request'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1411:in `catch'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1411:in `transport_request'
        from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1384:in `request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:999:in `request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http_persistent.rb:26:in `perform_request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http_persistent.rb:22:in `with_net_http_connection'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
... 14 levels...
        from /var/www/apps/my_app/development/releases/20150530220331/app/models/chapter.rb:40:in `index_attachment'
        from /var/www/apps/my_app/development/releases/20150530220331/app/models/book.rb:55:in `block in index_attachments'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `each'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `method_missing'
        from /var/www/apps/my_app/development/releases/20150530220331/app/models/book.rb:55:in `index_attachments'
        from (irb):4:in `block in irb_binding'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `each'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `method_missing'
        from (irb):3
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
```

**Comment by karmi** [comment]
I googled your error a bit and found: https://github.com/sparklemotion/mechanize/issues/123, maybe have a look there.

I'd try with a different HTTP library (Patron, Typhoeus, Curb, ...)

**Comment by twigbranch** [comment]
I'll try another library...  how do I get elasticsearch-rails to pickup on the library?

**Comment by karmi** [comment]
I assume you have read the documentation in the README? https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#the-elasticsearch-client

**Comment by karmi** [comment]
And of course https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#transport-implementations

**Comment by twigbranch** [comment]
Sorry about that- I had seen that, but hadn't properly reloaded the test environment.   Thanks for your help.

**Comment by karmi** [comment]
Cool!

**Comment by twigbranch** [comment]
Patron loaded, but errors out, unfortunately.  I suppose I could, sleep between updates, catch the errors and retry after a short delay, or perhaps double the timeout.  Does that make sense?
```
Faraday::TimeoutError: Operation timed out after 5166 milliseconds with 0 out of -1 bytes received
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/patron-0.4.20/lib/patron/session.rb:201:in `handle_request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/patron-0.4.20/lib/patron/session.rb:201:in `request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/patron.rb:33:in `call'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.11/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.11/lib/elasticsearch/transport/transport/base.rb:190:in `call'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.11/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.11/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.11/lib/elasticsearch/transport/client.rb:119:in `perform_request'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-api-1.0.11/lib/elasticsearch/api/actions/update.rb:98:in `block in update'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-api-1.0.11/lib/elasticsearch/api/utils.rb:189:in `__rescue_from_not_found'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/elasticsearch-api-1.0.11/lib/elasticsearch/api/actions/update.rb:97:in `update'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/store.rb:68:in `update'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/model/store.rb:125:in `block in update'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'
... 1 levels...
        from /var/www/apps/my_app/development/releases/20150531043059/app/models/chapter.rb:40:in `index_attachment'
        from /var/www/apps/my_app/development/releases/20150531043059/app/models/book.rb:55:in `block in index_attachments'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `each'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `method_missing'
        from /var/www/apps/my_app/development/releases/20150531043059/app/models/book.rb:54:in `index_attachments'
        from (irb):7:in `block in irb_binding'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `each'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/bundler/gems/elasticsearch-rails-738c63efacc1/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `method_missing'
        from (irb):7
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /var/www/apps/my_app/development/shared/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'
```

**Comment by karmi** [comment]
Moar README, @twigbranch :) https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#setting-timeouts
