### ISSUE TITLE
NoMethodError: undefined method `dump' for MultiJson:Module

### ISSUE THREAD

**Issue by aliahmed922** [elastic/elasticsearch-rails#453]
I am using Rails 3.1.10 with Ruby 1.9.3.
What the hell I am doing, It just made me totally sick.
I am using MongoDB with gem mongoid 2.2.
I have really tried alot it is always giving me this error I have the latest elastic search gem version and when I run
"Article.**elasticsearch**.client.cluster.health"

LoadError: cannot load such file -- {"cluster_name":"AliAhmed","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":5,"active_shards":5,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":5}
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.10/lib/active_support/dependencies.rb:234:in `load'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.10/lib/active_support/dependencies.rb:234:in`block in load'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.10/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.10/lib/active_support/dependencies.rb:640:in`new_constants_in'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.10/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.10/lib/active_support/dependencies.rb:234:in`load'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/serializer/multi_json.rb:24:in `load'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:230:in`perform_request'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in`perform_request'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/cluster/health.rb:49:in`health'
    from (irb):15
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.10/lib/rails/commands/console.rb:45:in `start'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.10/lib/rails/commands/console.rb:8:in`start'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.10/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'1.9.3-p551 :016 >

Also

Article.import
NoMethodError: undefined method `dump' for MultiJson:Module
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/utils.rb:87:in`block in __bulkify'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/utils.rb:77:in `map'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/utils.rb:77:in`__bulkify'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:75:in `bulk'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-model/lib/elasticsearch/model/importing.rb:123:in`block in import'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-model/lib/elasticsearch/model/adapters/mongoid.rb:69:in `block in __find_in_batches'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-model/lib/elasticsearch/model/adapters/mongoid.rb:68:in`each_slice'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-model/lib/elasticsearch/model/adapters/mongoid.rb:68:in `__find_in_batches'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-model/lib/elasticsearch/model/importing.rb:122:in`import'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-model/lib/elasticsearch/model.rb:115:in `import'
    from (irb):14
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.10/lib/rails/commands/console.rb:45:in`start'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.10/lib/rails/commands/console.rb:8:in `start'
    from /home/aliahmed/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.10/lib/rails/commands.rb:40:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

Please help me with this.

**Comment by aliahmed922** [comment]
@karmi what is the problem with multi_json dependency? elastic-search is not working with rails 3.1.10 and Mongoid
