### ISSUE TITLE
Incompatibility with Typhoeus gem?

### ISSUE THREAD

**Issue by hansy** [elastic/elasticsearch-rails#481]
I've been having problems communicating with ElasticSearch while using the `elasticsearch-persistence` gem. Turns out the culprit was [Typhoeus](https://github.com/typhoeus/typhoeus). The error I kept receiving was: `Ethon::Errors::InvalidOption: The option: disable_ssl_peer_verification is invalid`. 

Removing Typhoeus seemed to mitigate the issue. However I'd like to continue using Typhoeus elsewhere in my application. Thoughts on the root issue?

Here's my backtrace:

```
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy.rb:238:in `block in set_attributes'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy.rb:235:in `each_pair'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy.rb:235:in `set_attributes'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/http/actionable.rb:102:in `setup'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/http/post.rb:16:in `setup'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/http.rb:39:in `http_request'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/easy_factory.rb:51:in `get'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/addable.rb:19:in `add'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/memoizable.rb:41:in `add'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/cacheable.rb:10:in `add'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/block_connection.rb:30:in `add'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/stubbable.rb:23:in `add'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/before.rb:27:in `add'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/queueable.rb:77:in `dequeue_many'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/runnable.rb:14:in `run'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/memoizable.rb:51:in `run'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:23:in `perform_request'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:14:in `call'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:191:in `call'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:191:in `perform_request'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in `perform_request'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/index.rb:99:in `index'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-persistence-0.1.8/lib/elasticsearch/persistence/repository/store.rb:21:in `save'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-persistence-0.1.8/lib/elasticsearch/persistence/model/store.rb:58:in `block in save'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-persistence-0.1.8/lib/elasticsearch/persistence/model/store.rb:51:in `save'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-persistence-0.1.8/lib/elasticsearch/persistence/model/store.rb:22:in `block in create'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_create_callbacks'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-persistence-0.1.8/lib/elasticsearch/persistence/model/store.rb:21:in `create'
```

**Comment by karmi** [comment]
Hi, Typhoeus is definitely supported -- see https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#transport-implementations, there's a test for that as well: https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/test/integration/transport_test.rb#L18

There might be a problem with older versions of Faraday / Typhoeus, note that you need to do:

```
require 'typhoeus'; require 'typhoeus/adapters/faraday'
```

in order to load proper adapter. Can you try it and report back?

**Comment by toao** [comment]
Just stumbled upon the same issue. Requiring "typhoeus/adapters/faraday" as suggested by @karmi fixed it, thanks!

**Comment by tvcam** [comment]
Was having the same issue, thanks @karmi, it fixed the issue.

**Comment by shobhitvdb** [comment]
I was also having the same issue and the above solution fixed the issue
