### ISSUE TITLE
[MODEL] Isolate pagination libraries in tests

### ISSUE THREAD

**Issue by miguelff** [elastic/elasticsearch-rails#523]
While debugging the problem described in https://github.com/elastic/elasticsearch-rails/issues/476 I found that when running the test suite, both Kaminari and WillPaginate are included in `Elasticsearch::Model::Response`.

This make tests pretty indeterministic. For instance, while running `test/unit/response_pagination_kaminari_test.rb` we should check assertions over responses that only have kaminari pagination enabled, but if the test is run as part of the whole suite, `Elasticsearch::Model::Response` will have also WillPaginate features included.

I discovered this, while running the suite after a change in the code :

```
    ERROR (0:00:01.981) test_: Multimodel response pagination records should return previous page and next page.
          undefined local variable or method `max_pages' for #<Elasticsearch::Model::Response::Response:0x007f8438e29050>
        @ /Users/miguel/.rvm/gems/ruby-2.1.6/gems/kaminari-0.16.3/lib/kaminari/models/page_scope_methods.rb:27:in `total_pages'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/kaminari-0.16.3/lib/kaminari/models/page_scope_methods.rb:62:in `last_page?'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/kaminari-0.16.3/lib/kaminari/models/page_scope_methods.rb:47:in `next_page'
          lib/elasticsearch/model/response/pagination.rb:118:in `next_page'
          test/unit/response_pagination_kaminari_test.rb:425:in `block (3 levels) in <class:ResponsePaginationKaminariTest>'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1265:in `run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:884:in `_run_anything'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1092:in `run_tests'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1079:in `block in _run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1078:in `each'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1078:in `_run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:802:in `block in autorun'
```

The test `test/unit/response_pagination_kaminari_test.rb:423` was erroring due to a method missing, that was being delegated by WillPaginate (While the test is covering Kaminari pagination :rotating_light:)

However, when run in isolation, the test fails differently:

```
ERROR (0:00:02.074) test_: Response pagination records should return previous page and next page.
          undefined method `find' for Elasticsearch::Model::ResponsePaginationKaminariTest::ModelClass:Class
        @ lib/elasticsearch/model/adapters/default.rb:18:in `records'
          lib/elasticsearch/model/response/records.rb:58:in `method_missing'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/kaminari-0.16.3/lib/kaminari/models/page_scope_methods.rb:27:in `total_pages'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/kaminari-0.16.3/lib/kaminari/models/page_scope_methods.rb:62:in `last_page?'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/kaminari-0.16.3/lib/kaminari/models/page_scope_methods.rb:47:in `next_page'
          test/unit/response_pagination_kaminari_test.rb:224:in `block (3 levels) in <class:ResponsePaginationKaminariTest>'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
          /Users/miguel/.rvm/gems/ruby-2.1.6/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1265:in `run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:884:in `_run_anything'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1092:in `run_tests'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1079:in `block in _run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1078:in `each'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1078:in `_run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
          /Users/miguel/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:802:in `block in autorun'
```

The goal of this issue is to gather ideas on how can we setup a controlled, deterministic fixture for running the tests.

**Comment by karmi** [comment]
Yeah, this seems really brittle. Can we do something as easy as `remove_const` in the test, and use `gem` / `load` to force-load the library needed for the test? (Not sure, just throwing out ideas...)

**Comment by estolfo** [comment]
I'm going to close this as it's no longer relevant with the restructure and refactor of the tests to rspec. See commit https://github.com/elastic/elasticsearch-rails/commit/e72e02ca3eefef1e6af673456ec28b90e0e5c873
