### ISSUE TITLE
search(term) results in NullPointerException on elastic server 2.1

### ISSUE THREAD

**Issue by zigolab** [elastic/elasticsearch-rails#525]
After I upgraded to 2.1.1 version of Elasticsearch, when I try 

```
myModel.search("text to search") 
```

I get NullPointerException on the server. 
Same problem if I try 

```
myModel.search(query: {match: {_all: "text to search"}}).
```

No error if I try with every field as in

```
myModel.search({bool:{should:[{term:{field1:"text to search"}},{term:{field2:"text to search"}},{term:{field3:"text to search"}}]}}
```

If I downgrade to 2.0 version I have no problem at all.

These are my gemfile.lock libraries:

```
elasticsearch (1.0.14)
  elasticsearch-api (= 1.0.14)
  elasticsearch-transport (= 1.0.14)
elasticsearch-api (1.0.14)
  multi_json
elasticsearch-model (0.1.8)
  activesupport (> 3)
  elasticsearch (> 0.4)
  hashie
elasticsearch-rails (0.1.8)
elasticsearch-transport (1.0.14)
  faraday
  multi_son
```

This is a sample of the error on the server:

```
2016-01-26 08:22:06,436][INFO ][rest.suppressed          ] //controller/_search Params: {index=containers, type=model}
Failed to execute phase [query], all shards failed; shardFailures {[Y3EgJb3OSpWVYau6KY9JDA][containers][0]: RemoteTransportException[[Yith][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException; }{[Y3EgJb3OSpWVYau6KY9JDA][containers][1]: RemoteTransportException[[Yith][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException; }{[Y3EgJb3OSpWVYau6KY9JDA][containers][2]: RemoteTransportException[[Yith][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException; }{[Y3EgJb3OSpWVYau6KY9JDA][containers][3]: RemoteTransportException[[Yith][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException; }{[Y3EgJb3OSpWVYau6KY9JDA][containers][4]: RemoteTransportException[[Yith][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException; }
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
    at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
    at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: ; nested: NullPointerException;
    at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:382)
    at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:152)
    at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:99)
    at java.lang.Throwable.printStackTrace(Throwable.java:665)
    at java.lang.Throwable.printStackTrace(Throwable.java:721)
    at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
    at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
    at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
    at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
    at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
    at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
    at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
    at org.apache.log4j.Category.callAppenders(Category.java:206)
    at org.apache.log4j.Category.forcedLog(Category.java:391)
    at org.apache.log4j.Category.log(Category.java:856)
    at org.elasticsearch.common.logging.log4j.Log4jESLogger.internalInfo(Log4jESLogger.java:125)
    at org.elasticsearch.common.logging.support.AbstractESLogger.info(AbstractESLogger.java:90)
    at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:131)
    at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
    at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:87)
    at org.elasticsearch.rest.action.support.RestActionListener.onFailure(RestActionListener.java:60)
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.raiseEarlyFailure(TransportSearchTypeAction.java:316)
    ... 10 more
Caused by: java.lang.NullPointerException
    at org.apache.lucene.index.OrdTermState.copyFrom(OrdTermState.java:37)
    at org.apache.lucene.codecs.BlockTermState.copyFrom(BlockTermState.java:56)
    at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat$IntBlockTermState.copyFrom(Lucene50PostingsFormat.java:475)
    at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:1014)
    at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:152)
    at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:102)
    at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
    at org.apache.lucene.search.BooleanWeight.booleanScorer(BooleanWeight.java:201)
    at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:233)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:769)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
    at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:324)
    at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
    at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:375)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    ... 3 more
```

**Comment by Ashviniv** [comment]
@zigolab I think the problem is in elasticsearch server start. It might not start properly. Because I am using the same `2.1.1 version` of elasticsearch and the query is also correct except the last closing bracket. This query works for me.
