### ISSUE TITLE
Adding ElasticSearch breaks FactoryGirl with `wrong number of arguments (1 for 0)`

### ISSUE THREAD

**Issue by Startouf** [elastic/elasticsearch-rails#561]
It seems whenever I add the ElasticSearch includes in my models, it breaks my factories.

```
class Foo
  include Mongoid::Document
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  index_name "foo-#{Rails.env}"
end
```

    C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/factory_girl-4.7.0/lib/factory_girl/linter.rb:12:in `lint!': The following factories are invalid: (FactoryGirl::InvalidFactoryError)

> * foo - wrong number of arguments (1 for 0) (ArgumentError)

 ```
from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/factory_girl-4.7.0/lib/factory_girl.rb:67:in `lint'
        from C:/Dev/myjobglasses/spec/rails_helper.rb:52:in `block (2 levels) in <top (required)>'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:350:in `run'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `block in run'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `each'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `run'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:500:in `run'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:110:in `block in run_specs'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
        from C:/Dev/Ruby22-x64/bin/rspec:23:in `load'
        from C:/Dev/Ruby22-x64/bin/rspec:23:in `<main>'
```

I have tried adding this in my spec_helper, but it didn't change anything...

```
config.before(:each) do
      Foo.__elasticsearch__.create_index!(force: true)
  end
```
Are there any other precautions to take when using FactoryGirl with ElasticSearch models ?

- elasticsearch (1.0.17), elasticsearch-rails (0.1.8)
- rspec 3.1.7
- rails 5.0.0beta3

**Comment by Startouf** [comment]
So there was actually a problem in the model class, I had forgotten to add the options when overriding the `as_indexed_json`. Sorry about that, closing.

```
class Company
  ...
  def as_indexed_json(options = {}) # I had forgotten the options = {} here
    as_json(except: [:id, :_id, :verified])
  end
```

**Comment by colorfulberry** [comment]
@Startouf 
when i use 
config.before(:each) do
      Foo.__elasticsearch__.create_index!(force: true)
  end

Canot add any created data to elasticsearch in Rspec
