### ISSUE TITLE
using body in a search generate a timeout

### ISSUE THREAD

**Issue by mfutech** [elastic/elasticsearch-rails#590]
I use ruby 2.2.5, elasticsearch 1.0.18, patron 0.7.0 (same problem without patron)

Connection and simple query works: 
```
irb(main):008:0> x = c.cluster.health; x.class
=> Hash
irb(main):009:0> x = c.search index: 'logstash-2016.07.05'; x.class
=> Hash
irb(main):010:0> x = c.search index: 'logstash-2016.07.05'; x['hits']['hits'].length
=> 10
irb(main):011:0> x = c.search index: 'logstash-2016.07.05', size: 5; x['hits']['hits'].length
=> 5
irb(main):012:0> x = c.search index: 'logstash-2016.07.05', size: 5, q: 'test' ; x['hits']['hits'].length
=> 5
```

but as soon as I try to use body: and more complex queries I get a timeout at the transport layer. 

```
 irb(main):014:0> x = c.search index: 'logstash-2016.07.05', size: 5, body: { query: { match: [ { request: 'test' } ] } } ; x['hits']['hits'].length
Faraday::TimeoutError: Operation timed out after 5001 milliseconds with 0 bytes received
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/patron-0.7.0/lib/patron/session.rb:327:in `handle_request'
        from /home/marc/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/patron-0.7.0/lib/patron/session.rb:327:in `request'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/patron.rb:33:in `call'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:257:in `call'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
        from /home/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/search.rb:172:in `search'
        from (irb):14
        from /home/.rbenv/versions/2.2.5/bin/irb:11:in `<main>'
irb(main):015:0> 
```
Any idea on what can cause this issue ?

**Comment by mfutech** [comment]
related to elasticsearch-ruby not rails sorry.
