### ISSUE TITLE
Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes

### ISSUE THREAD

**Issue by SchlauFuchs** [elastic/elasticsearch-rails#606]
Hi,

I am trying a bulk import using an ActiveRecord class including ElasticSearch::Model using the function `import`.
I can see a call 
`2016-07-27 12:52:24 +1200: POST http://localhost:9200/myindex/myclass/_bulk [status:200, request:0.159s, query:0.150s]
2016-07-27 12:52:24 +1200: > {"index":{"_id":794719072}}`
and lots of json lines, then
lots of 
`2016-07-27 12:52:24 +1200: < {"took":150,"errors":true,"items":[{"index":{"_index":"myindex","_type":"myclass","_id":"794719072","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}},`

On the elasticsearch log side I  can see:
`[2016-07-27 12:52:24,427][DEBUG][action.bulk              ] [Hybrid] [myindex][4] failed to execute bulk item (index) index {[myindex][myclass][794720051], source[_na_]}
MapperParsingException[failed to parse]; nested: NotXContentException[Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:85)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XContentHelper.java:50)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:90)
        ... 18 more`

This happens on ElasticSearch 2.3.4 using elasticsearch-model 0.1.9.

**Comment by karmi** [comment]
Hi, I'm not familiar with the error, but this looks like a problem with the mapping. Can you verify that you mapping is correct and potentially paste it here for other to inspect?

**Comment by SchlauFuchs** [comment]
Hi, It is not the mapping as when I import them doc by doc using as
statement like
```MyEntity.find_each{|h|h.__elasticsearch__.index_document}```
 everything is processing fine.
Which doesn't mean that my mapping is perfect yet.

**Comment by mtomov** [comment]
Hello,

This error actually occurs if you pass in a `string` instead of a `json` document to the `body[n]data` key. 

Maybe something in the bulk api code transforms the string into something else and then sends it to elastic, while it doesn't do the same when using `index_document`. `index_document` works even with a plain string.

**Comment by geekpete** [comment]
Looks like a fix was merged for this: 

```Binary fields indexed into an upgraded (from 1.x -> 2.x) index hit "Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes" exception```

https://github.com/elastic/elasticsearch/pull/21440

**Comment by karmi** [comment]
Thanks for the link, @geekpete! @SchlauFuchs, is it OK to close the issue?

**Comment by chadfurman** [comment]
This issue is present in the source I pulled following the tutorial here:https://documentation.wazuh.com/1.1/ossec_elk_elasticsearch.html#ossec-elk-elasticsearch

**Comment by Laykou** [comment]
Note: @mtomov 's [answer above helped us](https://github.com/elastic/elasticsearch-rails/issues/606#issuecomment-259675889). In our case we were sending `nil`. So we just need to make sure to always send a hash :) Thx

**Comment by estolfo** [comment]
Closing as this has been resolved. See the comments above for solutions.

**Comment by xiao-ma-nong** [comment]
用实体类存就可以了
