### ISSUE TITLE
NoMethodError (as_indexed_json) on ElasticSearch::Model::import

### ISSUE THREAD

**Issue by welkie** [elastic/elasticsearch-rails#673]
I'm trying to use this gem in a Rails 5 app. I wanted to use MongoDB as my persistence layer and so I'm using the Mongoid ORM. I wonder if that may be the cause of my error.

According to the instructions, it's a good idea to import the data, so I run ```Actor.import force: true``` (force because there is no ES index yet) and I get:

```
NoMethodError: undefined method `as_indexed_json' for #<Actor:0x00000004233c60>
	from /var/lib/gems/2.3.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/adapters/mongoid.rb:74:in `block in __transform'
	from /var/lib/gems/2.3.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/importing.rb:144:in `block in __batch_to_bulk'
	from /var/lib/gems/2.3.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/importing.rb:144:in `map'
	from /var/lib/gems/2.3.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/importing.rb:144:in `__batch_to_bulk'
	from /var/lib/gems/2.3.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/importing.rb:126:in `block in import'
	from /var/lib/gems/2.3.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/adapters/mongoid.rb:69:in `block in __find_in_batches'
	from /var/lib/gems/2.3.0/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:696:in `yield_document'
	from /var/lib/gems/2.3.0/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:133:in `block in each'
	from /var/lib/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:45:in `block in each'
	from /var/lib/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `block in each'
	from /var/lib/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
	from /var/lib/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
	from /var/lib/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each'
	from /var/lib/gems/2.3.0/gems/mongoid-6.1.0/lib/mongoid/query_cache.rb:222:in `each'
	from /var/lib/gems/2.3.0/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:132:in `each'
	from /var/lib/gems/2.3.0/gems/mongoid-6.1.0/lib/mongoid/contextual.rb:20:in `each'
... 6 levels...
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/mwelke/Projects/elastic-search-tester/bin/rails:9:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

I was wondering if anyone knew what might be going on here or if it's just me trying to use this with Mongoid and that combination not being supported.

**Comment by karmi** [comment]
So, the gem relies on `as_json` method being defined in the model, and I'm wondering whether Mongoid didn't get rid of that method? Can you try running this [isolated example](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/mongoid_article.rb) with the exact versions you're using and see if it's OK Or not?

**Comment by welkie** [comment]
Ah I see. So it's probably not that hard to fix. I guess I just have to provide my own implementation of ```as_json```. I guess that's easier than manually writing all the code for ES CRUD operations and syncing, etc.

Perhaps it should be in the documentation that Mongoid users will need to manually implement ```as_json``` on their models?

**Comment by karmi** [comment]
> Perhaps it should be in the documentation that Mongoid users will need to manually implement as_json on their models?

Yeah, but I need to check it out, and update the example (and implementation, of course), depending on what I find... I don't recall 100%, but I bet Mongoid _had_ `as_json` defined for the models.

**Comment by karmi** [comment]
@welkie, just define the `as_indexed_json` method in your model -- apart from the most trivial cases, you will want to control how your model is serialized for Elasticsearch anyway...

**Comment by cpalafox** [comment]
if you implement `as_indexed_json`, does it still take into consideration the custom mappings you define?

Say... 

```
  def as_indexed_json(options={})
    self.as_json({only: [:name, :description, :type, :user_id]})
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name
      indexes :description
      indexes :type
      indexes :user_id
    end
  end
```

isn't this redundant? Am I missing something?

**Comment by estolfo** [comment]
@cpalafox Is this question still relevant? If so, can you clarify what you mean when you ask if `as_indexed_json` takes the custom mappings into account?

**Comment by estolfo** [comment]
Closing because of no response.
