### ISSUE TITLE
occasionally seeing wrong argument type Module (expected Proc)

### ISSUE THREAD

**Issue by alrooney** [elastic/elasticsearch-rails#711]
I'm occasionally getting this error when creating a document as follows:

```
Elasticsearch::Client.new.create(index: writer_alias, type: klass_name, id: SecureRandom.urlsafe_base64, body: params)
```

Anyone else see this?  Any ideas?

Here's where the exception is raised:

```
TypeError·wrong argument type Module (expected Proc)
Full TraceRaw
vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:100 adapter	
    def adapter(key, *args, &block)
      use_symbol(Faraday::Adapter, key, *args, &block)
    end
    ## methods to push onto the various positions in the stack:
```

And here's the relevant stack trace:
```
vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:100:in `adapter': wrong argument type Module (expected Proc) (TypeError)
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:117:in `block in initialize'
    from vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:91:in `initialize'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `new'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `__build_connection'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:137:in `block in __build_connections'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:129:in `map'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:129:in `__build_connections'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:39:in `initialize'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:114:in `new'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:114:in `initialize'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport.rb:26:in `new'
    from vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport.rb:26:in `new'
```

**Comment by estolfo** [comment]
Hi @alrooney Is this still an issue? It looks like from the stacktrace it should be reported in the [elasticsearch-ruby project](https://github.com/elastic/elasticsearch-ruby). Let me know if you've found a solution. Thanks
