### ISSUE TITLE
IndexAlreadyExistsException during tests while recreating index

### ISSUE THREAD

**Issue by jordan-brough** [elastic/elasticsearch-rails#718]
The following code from v2.0.1 of elasticsearch-rails does not seem to work 100% reliably for me in my specs.

The problem happens sporadically (rarely) during a call to:
```ruby
MyModel.import(force: true, refresh: true)
```
The code from elasticsearch-model that is failing is:
```ruby
def create_index!(options={})
  target_index = options.delete(:index) || self.index_name

  # NOTE: `options[:force]` is `true`
  #       (from `MyModel.import(force: true, refresh: true)`)
  delete_index!(options.merge index: target_index) if options[:force]

  unless index_exists?(index: target_index)
    #
    # *****PROBLEM HAPPENS HERE*****
    # The next line sometimes fails with an `IndexAlreadyExistsException` error.
    #
    self.client.indices.create index: target_index,
                               body: {
                                 settings: self.settings.to_hash,
                                 mappings: self.mappings.to_hash }
  end
end
```
See the code comment above ^

How could that error happen since the code checks for index existence on the previous line?

The full error is:
```
Elasticsearch::Transport::Transport::Errors::BadRequest:
  [400] {"error":"RemoteTransportException[[Thane Ector][inet[/10.0.3.30:9300]][indices/create]]; nested: IndexAlreadyExistsException[[my-model] already exists]; ","status":400}
```
With this backtrace:
```
/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'
/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/transport/base.rb:313:in `perform_request'
/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/client.rb:128:in `perform_request'
/elasticsearch-api-2.0.2/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/elasticsearch-api-2.0.2/lib/elasticsearch/api/actions/indices/create.rb:84:in `create'
/elasticsearch-model-2.0.1/lib/elasticsearch/model/indexing.rb:228:in `create_index!'
/elasticsearch-model-2.0.1/lib/elasticsearch/model/importing.rb:116:in `import'
/elasticsearch-model-2.0.1/lib/elasticsearch/model.rb:117:in `import'
```

**Comment by estolfo** [comment]
@jordan-brough Is this still an issue or have you been able to resolve it?

**Comment by jordan-brough** [comment]
I'm no longer working with this code so I'm not sure. Closing.
