### ISSUE TITLE
Bulk issue - request timed out

### ISSUE THREAD

**Issue by zauzaj** [elastic/elasticsearch-rails#744]
Hi,

I have observer which update elasticsearch according to changes on our app:

```
    def perform(ids, type)
      puts "================type: #{type}, ids: #{ids}, count: #{ids.count}==============="
      batches = []
      index_name = Staff.index_name
      Staff.active_and_searchable.where(id: ids).each do |record|
        batches.push({
          update: {
            _index: index_name,
            _type:  "staff",
            _id:    record.id,
            data: {
              doc: { next_availability_in_days: record.next_availability_in_days }
            }
          }
        })
      end
      Staff.__elasticsearch__.client.bulk(
        body: batches
      )
    end
```
And everything worked just fine but now I've noticed that Sidekiq thrown an error:
```
2017-10-05T12:27:38Z 25526 TID-os2tgpqms WARN: request timed out
2017-10-05T12:27:38Z 25526 TID-os2tgpqms WARN: /var/www/openhand/shared/bundle/ruby/2.1.0/gems/typhoeus-1.1.2/lib/typhoeus/adapters/faraday.rb:100:in `block in request'
................
/var/www/openhand/shared/bundle/ruby/2.1.0/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
/var/www/openhand/releases/20171005091601/app/workers/elastic_search/agenda_sync_worker.rb:22:in `perform'
```
Seems like it fails on this line in SidekiqWorker `Staff.__elasticsearch__.client.bulk` 

Last what we did is upgrading Redis to 3 but on my local machine I've already used such version and everything works just fine ! 

Any help would appreciate,

Thanks .

**Comment by estolfo** [comment]
@zauzaj Is this still an issue or have you resolved it?

**Comment by zauzaj** [comment]
@estolfo Hi, yes I did resolve. It was kind of typo. 

I'm closing it now .
