### ISSUE TITLE
ElasticSearch 6 gem Coliding with mongoid gem after upgrade to Ralis 6 

### ISSUE THREAD

**Issue by equivalent** [elastic/elasticsearch-rails#904]
I noticed this bug after upgraded from Rails 5 to Rails 6 and getting:

```
/home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant WillPaginate::CollectionMethods (NameError)
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model/response/pagination/will_paginate.rb:14:in `included'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model.rb:44:in `include'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model.rb:44:in `<main>'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:95:in `rescue in block in require'
	from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:72:in `block in require'
	from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler.rb:114:in `require'
	from /home/t/git/pobble/pobble-api/config/application.rb:24:in `<top (required)>'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/spring-2.1.0/lib/spring/application.rb:92:in `require'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/spring-2.1.0/lib/spring/application.rb:92:in `preload'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /home/t/.rvm/gems/ruby-2.6.3@pobble-api/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

now here is funny thing I don't use `WillPaginate` in my project but I'm using `mongoid` gem which uses [leshill-will_paginate](https://github.com/leshill/will_paginate)  which doesn't contain `WillPaginate::CollectionMethods`

so in `elasticsearch-model-6.1.0/lib/elasticsearch/model/response/pagination/will_paginate.rb` there is a code:

```
  module Model
    module Response
 
      # Pagination for search results/records
      #
      module Pagination
 
 
        # Allow models to be paginated with the "will_paginate" gem [https://github.com/mislav/will_paginate]
        #   
        module WillPaginate
          def self.included(base)
            base.__send__ :include, ::WillPaginate::CollectionMethods  # <<<<< HERE
 
            # Include the paging methods in results and records
            #
            methods = [:current_page, :offset, :length, :per_page, :total_entries, :total_pages, :previous_page, :next_page, :out_of_bounds?]
            Elasticsearch::Model::Response::Results.__send__ :delegate, *methods, to: :response
            Elasticsearch::Model::Response::Records.__send__ :delegate, *methods, to: :response
          end
# ...
```

So I don't know if this is Mongoid bug or ElasticSearch Model bug :)  and sorry for the title but I was up to date and only after upgrade from Rails 5.2 to Rails 6.0.0 this suddenly was the issue (didn't upgrade mongoid nor ES gem)

* mongoid (1.0.6)
* ruby 2.6.3
* rails 6.0.0
*  elasticsearch-rails (6.1.0)
*  elasticsearch-model (6.1.0)

**Comment by equivalent** [comment]
when trying to upgrade mongoid to latest version 

```
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 6.0.0)

  In Gemfile:
    elasticsearch-persistence (~> 6.0) was resolved to 6.1.0, which depends on
      activemodel (> 4)

    mongoid (~> 7.0.4) was resolved to 7.0.4, which depends on
      activemodel (>= 5.1, < 6.0.0)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      activemodel (= 6.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

:thinking:

**Comment by estolfo** [comment]
@equivalent I believe Mongoid will have to be released with Rails 6 support in order for this to be resolved.

**Comment by equivalent** [comment]
I can confirm that once I used `gem 'mongoid', git: 'git@github.com:Fudoshiki/mongoid.git'` this is no longer issue

to provide context `Fudoshiki/mongoid` mongoid master fork with pending PR for https://github.com/mongodb/mongoid/pull/4649. So once they merge and release it all that is needed is use the latest `mongoid` and it will not be issue 

All ok for me now :+1:
