### ISSUE TITLE
Error "Method not implemented for default adapter" after update to Rails 6 with zeitwerk

### ISSUE THREAD

**Issue by diei** [elastic/elasticsearch-rails#920]
I have updated Rails from v5.2.4.1 to v6.0.2.1 and use the code loader "zeitwerk" now. Since then I get following error if I try to import my model `Person` with a custom adapter via a rake task:
```
$> CLASS=Person FORCE=true bundle exec rake environment elasticsearch:import:model
Elasticsearch::Model::NotImplemented: Method not implemented for default adapter
/Users/diei/.rvm/gems/ruby-2.6.5/gems/elasticsearch-model-5.1.0/lib/elasticsearch/model/adapters/default.rb:43:in `__transform'
/Users/diei/.rvm/gems/ruby-2.6.5/gems/elasticsearch-model-5.1.0/lib/elasticsearch/model/importing.rb:107:in `import'
/Users/diei/.rvm/gems/ruby-2.6.5/gems/elasticsearch-rails-5.1.0/lib/elasticsearch/rails/tasks/import.rb:63:in `block (3 levels) in <top (required)>'
/Users/diei/Projects/ohl/workspaces/ikos_api/lib/tasks/elasticsearch.rake:15:in `block (2 levels) in <top (required)>'
/Users/diei/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

My classes in Rails 5.2.4.1:

person.rb
```ruby
require 'elasticsearch/person/adapter'

class Person
  include ActiveModel::Model
  include ::Elasticsearch::Model
  include ::Elasticsearch::Person::Adapter

  attr_accessor :id, :name
end
```

elasticsearch/person/adapter.rb
```ruby
module Elasticsearch
  module Person
    module Adapter
      include ::Elasticsearch::Model::Adapter::Default

      ::Elasticsearch::Model::Adapter.register(
          self,
          lambda { |klass| !!defined?(::Person) && klass.respond_to?(:ancestors) && klass.ancestors.include?(::Person) }
      )

      module Importing
        def __find_in_batches(options = {}, &block)
          yield [::Person.new(id: 12, name: 'John')] # load people from anywhere
        end

        def __transform
          lambda { |model| {index: {_id: model.id, data: model.to_json}} }
        end
      end
    end
  end
end
```

Maybe the error occurs, because the class loader "zeitwerk" needs for each constant (classes and modules) a single file: https://github.com/fxn/zeitwerk#file-structure
And e. g. the `Elasticsearch::Model::Adapter::Default` contains three modules.

Is Rails 6.0 supported?

### Sytem configuration
ruby 2.6.5
rails 5.2.4.1 => working
rails 6.0.2.1 => not working
elasticsearch (5.0.5)
elasticsearch-api (5.0.5)
elasticsearch-model (5.1.0)
elasticsearch-rails (5.1.0)
elasticsearch-transport (5.0.5)

**Comment by diei** [comment]
I found a way to fix this. It belongs to the way how zeitwerk does the class loading. The `Elasticsearch::Person::Adapter` isn't registered at the time when the responsible Adapter for `Person` is requested from `::Elasticsearch::Model::Adapter.adapter`. Therefore I need to be sure that my custom adapter is registered before the class `Person` is loaded.

Prior in Rails 5 it was possible with `require`, but with zeitwerk you aren't allowed to use `require` for your own code, because zeitwerk takes care of everything.
Either, you can not register the adapter within an initializer, because class loading via initializers is deprecated.

I put the registration into the person.rb, before the class definition.

My classes in Rails 6.0.2.1:

person.rb
```ruby
::Elasticsearch::Model::Adapter.register(
    ::Elasticsearch::Person::Adapter,
    lambda { |klass| !!defined?(::Person) && klass.respond_to?(:ancestors) && klass.ancestors.include?(::Person) }
)

class Person
  include ActiveModel::Model
  include ::Elasticsearch::Model

  attr_accessor :id, :name
end
```

elasticsearch/person/adapter.rb
```ruby
module Elasticsearch
  module Person
    module Adapter
      include ::Elasticsearch::Model::Adapter::Default

      module Importing
        def __find_in_batches(options = {}, &block)
          yield [::Person.new(id: 12, name: 'John')] # load people from anywhere
        end

        def __transform
          lambda { |model| {index: {_id: model.id, data: model.to_json}} }
        end
      end
    end
  end
end
```
