### ISSUE TITLE
"Required argument 'index' missing" error during update index

### ISSUE THREAD

**Issue by s0rin** [elastic/elasticsearch-rails#963]
In Rails 6.0.3.2 the update index works as expected, but as soon as I replace in controller **update_attributes** method with **update** (due to https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/), then the following error occurs:

```ArgumentError in ClassificationsController#update

Required argument 'index' missing
Extracted source (around line #63):

#61       #
#62       def update(arguments={})
*63         raise ArgumentError, "Required argument 'index' missing" unless arguments[:index]
#64         raise ArgumentError, "Required argument 'type' missing"  unless arguments[:type]
#65         raise ArgumentError, "Required argument 'id' missing"    unless arguments[:id]
#66         method = HTTP_POST

Extracted source (around line #101):

#99         unless @classification.nil?
#100           respond_to do |format|
*101             if @classification.update(classification_params)
#102               LogDatum.start_logging(current_user, @classification, params[:action], LogDatum::LOGDATUM_CLASSIFICATION,
#103 @classification.subjectheadings.map(&:id))
#104               flash[:success] = t('activerecord.successful.messages.classification.update',

Extracted source (around line #205):

#203
#204       collector = Collector.new(mimes, request.variant)
*205       yield collector if block_given?
#206
#207       if format = collector.negotiate_format(request)
#208         if media_type && media_type != format 


Rails.root: [...]

Application Trace
app/controllers/classifications_controller.rb:101:in `block in update'
app/controllers/classifications_controller.rb:99:in `update'

**Comment by s0rin** [comment]
My mistake, I had **include Elasticsearch::API** in controller, after removing it the problem disappears.
