### ISSUE TITLE
Trying to create an index in db.seed running rspec fails

### ISSUE THREAD

**Issue by aleguro** [elastic/elasticsearch-rails#977]
**Under db/seeds.rb**

`Model.__elasticsearch__.create_index! force: true`

`$ bundle exec rspec --backtrace`

**Backtrace**

`ArgumentError:
  wrong number of arguments (given 0, expected 1)
# ./spec/support/graphql_helper.rb:32:in `query'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/request.rb:98:in `url'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:486:in `block in run_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:506:in `block in build_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/request.rb:57:in `block in create'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/request.rb:56:in `tap'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/request.rb:56:in `create'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:502:in `build_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:484:in `run_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/client.rb:182:in `perform_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-api-7.10.1/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-api-7.10.1/lib/elasticsearch/api/actions/indices/delete.rb:51:in `delete'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-model-7.1.1/lib/elasticsearch/model/indexing.rb:290:in `delete_index!'
# /Users/alejandrogurovich/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/elasticsearch-model-7.1.1/lib/elasticsearch/model/indexing.rb:248:in `create_index!'
# ./db/seeds.rb:274:in `<top (required)>'`

**Model**

class Model
    include Mongoid::Document
    include Mongoid::Attributes::Dynamic
    include Elasticsearch::Model

    def as_indexed_json(_options = {})
      as_json(only: %w[id name product_id product_variant_id])
    end
  end
end
`

**Comment by indirect** [comment]
I opened a PR with a fix for this. If you're impatient, you can update your Gemfile entry for `elasticsearch-model` to use the fix before they merge the fix and release a new version:

```ruby
gem "elasticsearch-model", github: "indirect/elasticsearch-rails"
```

**Comment by indirect** [comment]
(At least, I hope it's a fix! It seems like the same keyword arguments issue. If it's not, apologies.)

**Comment by aleguro** [comment]
Thanks for your help @indirect !
